package cn.edu.nuc.weibo.parsewb;

import cn.edu.nuc.weibo.R;

public class IDs {
	public static int[] ids = { R.drawable.zz2_org, R.drawable.fuyun_org,
		R.drawable.horse2_org, R.drawable.panda_org, R.drawable.rabbit_org,
		R.drawable.j_org, R.drawable.wg_org, R.drawable.vw_org,
		R.drawable.otm_org, R.drawable.hufen_org, R.drawable.liwu_org,
		R.drawable.laugh, R.drawable.good_org, R.drawable.cool_org,
		R.drawable.kl_org, R.drawable.sk_org, R.drawable.cj_org,
		R.drawable.cry, R.drawable.money_org, R.drawable.bz_org,
		R.drawable.bs2_org, R.drawable.sw_org, R.drawable.sb_org,
		R.drawable.qq_org, R.drawable.nm_org, R.drawable.mb_org,
		R.drawable.ldln_org, R.drawable.yhh_org, R.drawable.zhh_org,
		R.drawable.x_org, R.drawable.wq_org, R.drawable.t_org,
		R.drawable.k_org, R.drawable.d_org, R.drawable.yw_org,
		R.drawable.ws_org, R.drawable.ye_org, R.drawable.sad_org,
		R.drawable.no_org, R.drawable.ok_org, R.drawable.h_org,
		R.drawable.zy_org, R.drawable.sdz_org, R.drawable.lazu_org,
		R.drawable.sun, R.drawable.clock_org, R.drawable.come_org,
		R.drawable.cake, R.drawable.unheart, R.drawable.pig,
		R.drawable.m_org, R.drawable.moon, R.drawable.fan,
		R.drawable.yinyuehe_org, R.drawable.shoufa_org,
		R.drawable.nanguatou2_org, R.drawable.han_org,
		R.drawable.shoutao_org, R.drawable.weijin_org,
		R.drawable.geili_org, R.drawable.bingo_org, R.drawable.ai_org,
		R.drawable.nycake_org, R.drawable.xi_org, R.drawable.kawayi_org,
		R.drawable.ciya_org, R.drawable.semimi_org, R.drawable.kelian_org,
		R.drawable.twh_org, R.drawable.zy_org, R.drawable.qq_org,
		R.drawable.nm_org, R.drawable.mb_org, R.drawable.ldln_org,
		R.drawable.k_org, R.drawable.sb_org, R.drawable.sdz_org,
		R.drawable.sw_org, R.drawable.kl_org, R.drawable.h_org,
		R.drawable.t_org, R.drawable.wq_org, R.drawable.sk_org,
		R.drawable.laugh, R.drawable.x_org, R.drawable.yhh_org,
		R.drawable.zhh_org, R.drawable.yw_org, R.drawable.yx_org,
		R.drawable.d_org, R.drawable.money_org, R.drawable.bs_org,
		R.drawable.bs2_org, R.drawable.cj_org, R.drawable.bz_org,
		R.drawable.cry, R.drawable.fn_org, R.drawable.gm_org,
		R.drawable.cool_org, R.drawable.come_org, R.drawable.good_org,
		R.drawable.ha_org, R.drawable.no_org, R.drawable.ok_org,
		R.drawable.o_org, R.drawable.sad_org, R.drawable.ws_org,
		R.drawable.z2_org, R.drawable.ye_org, R.drawable.bad_org,
		R.drawable.right_org, R.drawable.left_org, R.drawable.pink_org,
		R.drawable.weijin_org, R.drawable.wennuanmaozi_org,
		R.drawable.shoutao_org, R.drawable.hongbao_org, R.drawable.xi_org,
		R.drawable.liwu_org, R.drawable.cake, R.drawable.r_org,
		R.drawable.diamond_org, R.drawable.dynamicbus_org,
		R.drawable.travel_org, R.drawable.zxc_org, R.drawable.jc_org,
		R.drawable.sj2_org, R.drawable.camera_org, R.drawable.y_org,
		R.drawable.dn_org, R.drawable.sz_org, R.drawable.christree_org,
		R.drawable.chrishat_org, R.drawable.chrisfather_org,
		R.drawable.chrisbell_org, R.drawable.chrisocks_org,
		R.drawable.yinyuehe_org, R.drawable.shoufa_org,
		R.drawable.muqinjie_org, R.drawable.tupianimage_org,
		R.drawable.liumangxing_org, R.drawable.diqiuxiuxiyixiaoshi_org,
		R.drawable.zhishujie_org, R.drawable.nycake_org,
		R.drawable.candy_org, R.drawable.nanguatou2_org, R.drawable.hj_org,
		R.drawable.wine_org, R.drawable.mooncake3_org,
		R.drawable.moon1_org, R.drawable.qkl_org, R.drawable.jy_org,
		R.drawable.j2_org, R.drawable.g_org, R.drawable.gz3_org,
		R.drawable.gz2_org, R.drawable.green_org, R.drawable.gq_org,
		R.drawable.foot_org, R.drawable.clock_org, R.drawable.cha_org,
		R.drawable.watermelon, R.drawable.umb_org, R.drawable.tv_org,
		R.drawable.tel_org, R.drawable.sun, R.drawable.star_org,
		R.drawable.shao, R.drawable.m_org, R.drawable.music_org,
		R.drawable.movie_org, R.drawable.moon, R.drawable.ktv_org,
		R.drawable.ice, R.drawable.house_org, R.drawable.hat_org,
		R.drawable.football, R.drawable.flower_org, R.drawable.flower,
		R.drawable.fan, R.drawable.cheer, R.drawable.cafe_org,
		R.drawable.rabbit_org, R.drawable.horse2_org, R.drawable.fuyun_org,
		R.drawable.geili_org, R.drawable.kawayi_org, R.drawable.pear_org,
		R.drawable.panda_org, R.drawable.hufen_org, R.drawable.wg_org,
		R.drawable.rjd_org, R.drawable.otm_org, R.drawable.vw_org,
		R.drawable.unheart, R.drawable.rw_org, R.drawable.j_org,
		R.drawable.orz1_org, R.drawable.z_org, R.drawable.xc_org,
		R.drawable.s2_org, R.drawable.pig, R.drawable.sx_org,
		R.drawable.kl2_org, R.drawable.s_org, R.drawable.xx2_org,
		R.drawable.yellowcard, R.drawable.redcard, R.drawable.twh_org,
		R.drawable.bingo_org, R.drawable.zt_org, R.drawable.th_org,
		R.drawable.wh_org, R.drawable.jh_org, R.drawable.dh_org,
		R.drawable.kissgirl_org, R.drawable.kissboy_org,
		R.drawable.newz_org, R.drawable.newy_org, R.drawable.newx_org,
		R.drawable.newv_org, R.drawable.newu_org, R.drawable.newt_org,
		R.drawable.news_org, R.drawable.newr_org, R.drawable.newq_org,
		R.drawable.newp_org, R.drawable.newn_org, R.drawable.newl_org,
		R.drawable.newk_org, R.drawable.newj_org, R.drawable.newh_org,
		R.drawable.newg_org, R.drawable.newf_org, R.drawable.newd_org,
		R.drawable.newa_org, R.drawable.weibow_org, R.drawable.weibop_org,
		R.drawable.weiboo_org, R.drawable.weibom_org,
		R.drawable.weiboi_org, R.drawable.weiboe_org,
		R.drawable.weiboc_org, R.drawable.weibob_org,
		R.drawable.shengluehao_org, R.drawable.kiss2_org,
		R.drawable.yuan_org, R.drawable.tuan_org, R.drawable.tuanyuan_org,
		R.drawable.zz2_org, R.drawable.liaobuqi_org,
		R.drawable.guanbuzhao_org, R.drawable.ai_org,
		R.drawable.youdiankun_org, R.drawable.yes_org,
		R.drawable.yanhuiqule_org, R.drawable.yalihenda_org,
		R.drawable.xiuxiu_org, R.drawable.xihuang_org,
		R.drawable.xiaobianpi_org, R.drawable.wunai22_org,
		R.drawable.tutu_org, R.drawable.tushetou_org,
		R.drawable.touyun_org, R.drawable.tingyinyue_org,
		R.drawable.shuijiao_org, R.drawable.shanshanzi_org,
		R.drawable.shanshanlu_org, R.drawable.shanshanhui_org,
		R.drawable.shanshanhong_org, R.drawable.shanshanfen_org,
		R.drawable.paoxiao_org, R.drawable.motou_org,
		R.drawable.meihao_org, R.drawable.lianhongzibao_org,
		R.drawable.kuqinv_org, R.drawable.kuqinan_org, R.drawable.kong_org,
		R.drawable.jinqingwan_org, R.drawable.jingxi_org,
		R.drawable.jingdai_org, R.drawable.huluobo_org,
		R.drawable.huangtengquai_org, R.drawable.ganmao_org,
		R.drawable.fennu_org, R.drawable.fendou123_org,
		R.drawable.faya_org, R.drawable.chunnuanhuakai_org,
		R.drawable.chouyan_org, R.drawable.ang_org, R.drawable.aa_org,
		R.drawable.zichashuangmu_org, R.drawable.yiwen_org,
		R.drawable.xu_org, R.drawable.wochiwode_org, R.drawable.weiqu_org,
		R.drawable.v5_org, R.drawable.tiaoxi_org,
		R.drawable.taihaoxiaole_org, R.drawable.shoujian_org,
		R.drawable.se_org, R.drawable.pen_org, R.drawable.nidongde_org,
		R.drawable.miaomiao_org, R.drawable.meiwei_org,
		R.drawable.jingkong_org, R.drawable.gandong_org,
		R.drawable.fangkai_org, R.drawable.chidai_org,
		R.drawable.chelian_org, R.drawable.buzhisuocuo_org,
		R.drawable.baiyan_org, R.drawable.weisuo_org,
		R.drawable.tiaomei_org, R.drawable.tiaodou_org,
		R.drawable.qinerduo_org, R.drawable.meiyan_org,
		R.drawable.maogepao_org, R.drawable.jiongerduo_org,
		R.drawable.guilian_org, R.drawable.fangdian_org,
		R.drawable.beiju_org, R.drawable.touch_org, R.drawable.sweat_org,
		R.drawable.suprise_org, R.drawable.supcry_org,
		R.drawable.stareyes_org, R.drawable.sleepy_org,
		R.drawable.sick_org, R.drawable.plus1_org, R.drawable.pipioye_org,
		R.drawable.muamua_org, R.drawable.mianchou_org,
		R.drawable.laugh_org, R.drawable.knead_org, R.drawable.jiong_org,
		R.drawable.honeyoye_org, R.drawable.happy_org,
		R.drawable.handkerchief_org, R.drawable.go_org,
		R.drawable.dizzy_org, R.drawable.cry_org, R.drawable.coverface_org,
		R.drawable.angery_org, R.drawable.w_org, R.drawable.tf_org,
		R.drawable.sc_org, R.drawable.qzdy_org, R.drawable.lx_org,
		R.drawable.ljf_org, R.drawable.hs2_org, R.drawable.gf_org,
		R.drawable.dyzq_org, R.drawable.ch_org, R.drawable.bb2_org,
		R.drawable.wind_org, R.drawable.sunny_org, R.drawable.snow_org,
		R.drawable.sh_org, R.drawable.rain, R.drawable.dark_org,
		R.drawable.byz2_org, R.drawable.ssz2_org, R.drawable.syz2_org,
		R.drawable.szz2_org, R.drawable.tpz2_org, R.drawable.txz2_org,
		R.drawable.spz2_org, R.drawable.cnz2_org, R.drawable.jnz2_org,
		R.drawable.jxz2_org, R.drawable.leo2_org, R.drawable.mjz2_org,
		R.drawable.txz_org, R.drawable.tpz_org, R.drawable.szz_org,
		R.drawable.syz_org, R.drawable.ssz_org, R.drawable.spz_org,
		R.drawable.mjz_org, R.drawable.leo_org, R.drawable.jxz_org,
		R.drawable.jnz_org, R.drawable.cnz_org, R.drawable.byz_org,
		R.drawable.yeah_org, R.drawable.xh_org, R.drawable.xd_org,
		R.drawable.wl_org, R.drawable.gx_org, R.drawable.gx2_org,
		R.drawable.gd_org, R.drawable.fn2_org, R.drawable.d2_org,
		R.drawable.bx_org, R.drawable.jiayou_org, R.drawable.flag_org,
		R.drawable.jinpai_org, R.drawable.yinpai_org,
		R.drawable.tongpai_org, R.drawable.shao, R.drawable.yellowcard,
		R.drawable.redcard, R.drawable.football, R.drawable.bball_org,
		R.drawable.black8_org, R.drawable.volleyball_org,
		R.drawable.swimming_org, R.drawable.pingpong_org,
		R.drawable.basketball_org, R.drawable.badminton_org,
		R.drawable.zuqiu_org, R.drawable.shejian_org,
		R.drawable.juzhong_org, R.drawable.jijian_org,
		R.drawable.fanzao_org, R.drawable.ciya_org, R.drawable.youqian_org,
		R.drawable.weixiao_org, R.drawable.shuaibao_org,
		R.drawable.shengqi_org, R.drawable.shengbing_org,
		R.drawable.semimi_org, R.drawable.pilao_org, R.drawable.miao_org,
		R.drawable.ku_org, R.drawable.kelian_org, R.drawable.jinzhang_org,
		R.drawable.jingya_org, R.drawable.jidong_org,
		R.drawable.jianqian_org, R.drawable.han_org, R.drawable.fendou_org,
		R.drawable.xrdz_org, R.drawable.whh_org, R.drawable.tq_org,
		R.drawable.sjdj_org, R.drawable.q_org, R.drawable.pz_org,
		R.drawable.pp_org, R.drawable.nh_org, R.drawable.mb2_org,
		R.drawable.lg_org, R.drawable.lb_org, R.drawable.lbs_org,
		R.drawable.kiss_org, R.drawable.kb_org, R.drawable.jgwb_org,
		R.drawable.hxgw_org, R.drawable.gx3_org, R.drawable.gg_org,
		R.drawable.fd_org, R.drawable.fc_org, R.drawable.dy_org,
		R.drawable.cn_org, R.drawable.cf_org, R.drawable.ceg_org,
		R.drawable.cdyn_org, R.drawable.bz2_org, R.drawable.bt_org,
		R.drawable.bs3_org, R.drawable.bgws_org, R.drawable.bf_org,
		R.drawable.bdw_org, R.drawable.bco_org, R.drawable.zy2_org,
		R.drawable.zs_org, R.drawable.wh2_org, R.drawable.ts_org,
		R.drawable.q3_org, R.drawable.lb2_org, R.drawable.kt_org,
		R.drawable.bya_org, R.drawable.bx2_org, R.drawable.zk_org,
		R.drawable.wq2_org, R.drawable.q2_org, R.drawable.mh_org,
		R.drawable.m2_org, R.drawable.j3_org, R.drawable.h2_org,
		R.drawable.f_org, R.drawable.c_org, R.drawable.bz3_org,
		R.drawable.bgp_org, R.drawable.xixi };
}
